// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2GWTbI7GKnyARdKR7vMAioUypjQKHxow',
    appId: '1:38966084632:android:3022879cbac9feb74b2f6d',
    messagingSenderId: '38966084632',
    projectId: 'bidbolt-5d325',
    databaseURL: 'https://bidbolt-5d325-default-rtdb.firebaseio.com',
    storageBucket: 'bidbolt-5d325.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaQTzKAq632RO9Z4lvD_a01wzWu_cx4Xw',
    appId: '1:38966084632:ios:3973c1a9c0208dc44b2f6d',
    messagingSenderId: '38966084632',
    projectId: 'bidbolt-5d325',
    databaseURL: 'https://bidbolt-5d325-default-rtdb.firebaseio.com',
    storageBucket: 'bidbolt-5d325.firebasestorage.app',
    iosClientId:
        '38966084632-2opifo22is3g5q71h02bd4ivtuip6c8f.apps.googleusercontent.com',
    iosBundleId: 'com.bidbolt.driver',
  );
}
